version: '3.3'
services:
  stable-diffusion:
    #build:
    #  context: ./docker
    #  dockerfile: Dockerfile
    image: ghcr.io/parzival-space/stable-diffusion:latest
    volumes:
      - ./data:/data:rw
    ports:
      - "7680:7680/tcp"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]